export const ApplicationPage = {
    property: 'adm_property',
    building: 'adm_Building',
    country: 'adm_country',
    state: 'adm_state',
    user: 'adm_user',
    permission: 'adm_permission',
    changepassword: 'adm_changepassword',
    role: 'adm_role',
    group_code: 'inv_groupcode',
    module: 'adm_module_',
    student:'adm_Student',
    jobcard:'adm_JobCard',
    weightCheck : 'adm_weight_check',
    palletPacking: 'adm_PalletPackingHeader',
    trailerLoading: 'adm_trailor-loading',
    attributeCheck : 'adm_attribute_check',
    permissioon:'adm_Permission',
    trailerInspection : 'adm_trailer_inspection',
    downtimeTracking: 'adm_downtime',
    preCheck:'adm_PreCheckList',
    productionOrder:'adm_ProductionOrder',
    liquidPreparation:'adm_liquid_Preparation',
    postCheck:'adm_PostCheckList',
    laborVariance: 'adm_labor-variance',
    bom: 'adm_bom',
    productionplanning:'pr_productionplanning',
    moduleGroup: 'adm_modulegroup',
    termsAndConditions: 'adm_terms_conditions',
    customer: 'inv_customer',
    product: 'inv_product',
    process: 'inv_process',
    salesOrder: 'inv_salesorder',
    purchaseOrder: 'adm_purchase_order',
    vendorMaster: 'adm_vendor_master',
    workflow: 'adm_workflow',
    inventoryType: 'inv_inventorytypes',
    inward: 'inv_inwards',
    outward: 'inv_outward',
    qualityParameter: 'adm_quality_parameter',
    materialRequisition: 'adm_material_requisition',
    location: 'adm_location',
    groupLineItem: 'adm_group_line_item',
    bomprocess: 'pr_bomprocess',
    designation: 'designation',
    projectmaster:'ProjectMasters',
    serviceCategory: 'adm_service_category',
    projectAssignment: 'adm_project_assignment',
    budgetEntryScreen: 'budgetMaster',
    actualInputScreen: 'adm_actual_input_screen',
    provisionalInputScreen: 'adm_provisional_input_screen',
    mtdreport: 'adm_mtd_report',
    ytdreport: 'adm_ytd_report',
    machine: 'inv_machine',
    product_group: 'pr_group',
    stockLedger: 'inv_stockledger',
    productionWorkOrder: 'pr_workorder_',
    monthlyProductionPlanning:'pr_monthlyproductionplanning',
    productionWorkDone: 'pr_workdone_',
    purchaseOrderPlanning: 'pu_orderplanning',
    purchaseInquiry: 'pu_purchaseinquiry_',
    inspection: 'inv_inspection',
    auditLog: 'adm_auditLog',
    floor: 'adm_floor',
    unit: 'adm_unit',
    zone: 'adm_zone',
    residentMaster: 'adm_resident_master',
    guestMaster: 'adm_guest_master',
    amenityMaster: 'adm_amenity_master',
    amenitySlotTemplate: 'adm_amenity_slot_template',
    bookingHeader: 'adm_booking_header',
};

export const PermissionType = {
    create: 'create',
    edit: 'edit',
    list: 'list',
    active: 'active'
};
